Added allowSyntheticDefaultImports typescript flag
Received the following build error:

Error: node_modules/@angular/compiler-cli/src/ngtsc/file_system/src/util.d.ts:9:8 - error TS1259: Module '"/home/kalle/dev/wharf/wharf-web/node_modules/typescript/lib/typescript"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

9 import ts from 'typescript';
         ~~

  node_modules/typescript/lib/typescript.d.ts:7607:1
    7607 export = ts;
         ~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.