Upgraded to Angular 13 & PrimeNG 13 (#125)
* npx @angular/cli@13 update

* Manually update remaining deps

* npx browserslist --update-db

* Added allowSyntheticDefaultImports typescript flag

Received the following build error:

Error: node_modules/@angular/compiler-cli/src/ngtsc/file_system/src/util.d.ts:9:8 - error TS1259: Module '"/home/kalle/dev/wharf/wharf-web/node_modules/typescript/lib/typescript"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

9 import ts from 'typescript';
         ~~

  node_modules/typescript/lib/typescript.d.ts:7607:1
    7607 export = ts;
         ~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

* Changed local proxy conf to be default conf

* Regen clients using Angular 13

* Upgrade primeng and primeicons

* Upgrade eslint

* Changed regen clients docs in README.md

* Updated CHANGELOG.md

* Fixed indentation

* Upgrade to PrimeNG v13.3.3

* Updated CHANGELOG.md